Feature/sisins 15
tecnologia-share/service-sisins2021 pull request #24
Opened 2021-03-22 03:39 UTC by Renan04lima

2021-03-22 13:14 UTC, Oosasukel requested changes

2021-03-22 13:14 UTC, rodrigogonn commented on docs/api/participants/create.md
> +  /api/registerl
Erro aqui na rota

2021-03-22 13:14 UTC, rodrigogonn commented on docs/api/participants/create.md
> +  `]`
Deixa uma linha vazia entre cada parametro, senão a visualização aqui no github fica zuada
![image](https://user-images.githubusercontent.com/58633356/111989587-bc3f9600-8af0-11eb-8832-2ecf4bfa92e2.png)

2021-03-22 13:14 UTC, rodrigogonn commented on docs/api/participants/create.md
> +    **Content:** `{ "message": "Ask not found." }`
Aqui ta vendo se as perguntas que ele ta respondendo existem, mas deveria retornar um erro diferente também caso esteja faltando alguma pergunta, fez uma requisição com menos perguntas, todas vão existir, mas não pode deixar passar sem responder todas que estão no banco

2021-03-22 13:14 UTC, rodrigogonn commented on src/__tests__/Participant.test.ts
> +  const asksRepository = connection.getRepository(Pergunta);
Pode apagar o comentário e criar uma task lá no Jira pra isso, no teste pode ficar assim mesmo

2021-03-22 13:14 UTC, rodrigogonn commented on src/__tests__/Participant.test.ts
> +  it('Should not be possible to create an account with asks that dont exist', async () => {
Falta adicionar o teste "Não deve ser possível criar uma conta se não enviar a resposta de todas as perguntas"

2021-03-22 13:14 UTC, rodrigogonn commented on src/__tests__/Participant.test.ts
> +  it('Should return 400 BAD REQUEST if sent a email that has already been confirmed', async () => {
Acho melhor retornar um redirect também ao invéz de um json, pq o participante que vai ver isso

2021-03-22 13:14 UTC, rodrigogonn commented on src/controllers/ParticipantsController.ts
> +  asksAnswers: [
Essa tipagem aqui ta dizendo que asksAnswers vai ser um array com 1 elemento só, pra tipar um array faz assim:

```ts
  asksAnswers: Array<{
      asksId: string;
      response: string;
    }>;
```

ou


```ts
  asksAnswers: {
      asksId: string;
      response: string;
    }[]
```

Mas pra objeto desse jeito é melhor usar o primeiro jeito, que é mais facil de entender

2021-03-22 13:14 UTC, rodrigogonn commented on src/controllers/ParticipantsController.ts
> +      senha: password,
Tem que encriptar o password antes de salvar ele no banco

2021-03-22 13:14 UTC, rodrigogonn commented on src/controllers/ParticipantsController.ts
> +    for (let i = 0; i < asksAnswers.length; i++) {
Aqui tem que ver se ele respondeu todas antes

2021-03-22 13:14 UTC, rodrigogonn commented on src/controllers/ParticipantsController.ts
> +      const isExist = await asksRepository.findOne(asksAnswers[i].asksId, {
Aqui é melhor vc puxar todas as perguntas uma vez em um objeto e ai ficar buscando nesse objeto, fazer um loop de chamadas pro banco é ruim

2021-03-22 13:14 UTC, rodrigogonn commented on src/controllers/ParticipantsController.ts
> +      link: `${process.env.URL_MAIL}${token}`,
Acho melhor colocar direto aqui mesmo essa URL_MAIL, colocar no env só quando for algo que mude de um ambiente pro outro

2021-03-22 13:14 UTC, Oosasukel commented on src/views/emails/verificationEmail.hbs
> +                    <p>Assim que clica no botão faça o login e escolhar os cursos que desejar até o dia 26/03</p>
'escolhar'

acho melhor não colocar data do negócio aqui, pra não ficar mudando o email, ser um email de confirmação que vai sempre servir

2021-03-22 13:14 UTC, Oosasukel commented on src/views/emails/verificationEmail.hbs
> +  <style type="text/css" rel="stylesheet" media="all">
Pra email o css tem que ser inline, se tiver na tag style alguns provedores de email tiram tudo, testa enviar esse email pro teu gmail, nos meus testes ficou tudo zuado o email e com css inline não

2021-03-22 13:14 UTC, Oosasukel commented on src/services/SendMailService.ts
> +      nodemailer.createTestAccount().then((account) => {
Coloca um @TODO aqui, pra mudar pro serviço real, tem que pedir rapido a autorização pra fazer pela aws, senão não vai dar tempo de eles aceitarem

2021-03-22 13:14 UTC, Oosasukel commented on src/routes.ts
> +routes.post('/api/register/', participantsController.create);
Essa barra do final não precisa

2021-03-22 13:14 UTC, Oosasukel commented on src/models/PerguntaParticipante.ts
> -    { orphanedRowAction: 'delete' }
Aqui é melhor deixar esse orphanedRowAction: 'delete'

2021-03-22 13:14 UTC, Oosasukel commented on src/models/PerguntaParticipante.ts
> -    { orphanedRowAction: 'delete' }
Ou teve alguma razão pra tirar?

2021-03-22 13:14 UTC, Oosasukel commented on src/controllers/ParticipantsController.ts
> +    await SendMailService.execute(email, 'Cadastro', variables, npsPath);
Envia o email depois da linha 135, pra caso der erro no banco, não enviou o email ainda

2021-03-22 13:14 UTC, Oosasukel commented on src/controllers/ParticipantsController.ts
> +          return _next(new AppError('Participant not found.', 400));
404

2021-03-22 13:14 UTC, Oosasukel commented on src/controllers/ParticipantsController.ts
> +          return _next(new AppError('Email already confirmed!'));
Retorna uma página pra pessoa também, pra caso clique de novo no link sem querer

2021-03-22 13:14 UTC, Oosasukel commented on src/controllers/ParticipantsController.ts
> +        response.redirect('https://associacaoshare.com.br/');
Coloca outro TODO aqui, pra gente retornar pra uma página específica, não pra login, pra uma página dizendo tipo "Teu email foi confirmado com sucesso, faça o login" algo assim

2021-05-12 12:54 UTC, Oosasukel requested changes

2021-05-12 12:54 UTC, Oosasukel commented on docs/api/participants/create.md
> +  `asksAnswers:` [ {
Aqui dá pra colocar assim:
![image](https://user-images.githubusercontent.com/58633356/117973838-3fb48100-b303-11eb-808e-efe775c2bf07.png)

ae fica formatado assim:

```ts
[
  {
    asksId: string,
    response: string
  }
]
```

2021-05-12 12:54 UTC, Oosasukel commented on src/controllers/ParticipantsController.ts
> +    const senha = await bcrypt.hash(password, 10);
Variável em português, talvez passwordHash

2021-05-12 12:54 UTC, Oosasukel commented on src/controllers/ParticipantsController.ts
> +      const answer = (asksAnswers as AsksAnswers[]).find(
Essa interface AsksAnswers pelo nome eu imagino que já é um array, ai parece que ta tipando como array de array, podia ser no singular o nome da interface pra representar uma pergunta só

2021-05-12 12:54 UTC, Oosasukel commented on src/controllers/ParticipantsController.ts
> +        const participante = await participantesRepository.findOne({
Aqui não precisa passar um objeto para o findOne quando quer buscar pelo id, só o valor já resolve

2021-05-12 12:54 UTC, Oosasukel commented on src/services/SendMailService.ts
> +    } catch (error) {
Da pra tirar o catch se ele não ta fazendo nada

2021-05-12 12:54 UTC, Oosasukel commented on src/services/SendMailService.ts
> +      nodemailer.createTestAccount().then((account) => {
Aqui da pra colocar no inicio do execute, pq é assícrono, ai lá da pra colocar um await antes, pra aguardar terminar, quando for usar o serviço de verdade não é assincrono, ai vai aqui mesmo

2021-05-12 12:54 UTC, Oosasukel commented on src/services/SendMailService.ts
> +      // console.log(error);
Da pra tirar o try catch aqui também, ja que não ta fazendo nada no catch

2021-05-12 22:19 UTC, Renan04lima commented on src/services/SendMailService.ts
> +    } catch (error) {
aparece isso quando tira o catch e não aparece a opção de ignorar 'Parsing error: 'finally' expected.eslint'

2021-05-12 22:59 UTC, Oosasukel commented on src/services/SendMailService.ts
> +    } catch (error) {
Mas tem que tirar o try também

2021-05-12 23:47 UTC, Renan04lima commented on src/services/SendMailService.ts
> +    } catch (error) {
mas se tirar o try dá erro nos testes

2021-05-13 12:20 UTC, Oosasukel commented on src/services/SendMailService.ts
> +    } catch (error) {
Então tem algo errado com os testes, se tá dando erro nisso ai, não podemos tratar um erro desse jeito, só fazendo nada se der errado

2021-05-14 13:50 UTC, Oosasukel approved these changes

2021-05-14 13:51 UTC, Oosasukel approved these changes

2021-05-14 15:30 UTC, merged